#Spring
spring:
  profiles:
    active: dev

# MyBatisPlus
mybatisPlus:
  mapperLocations: classpath:/mybatis/mappers/**/*Mapper.xml
  typeEnumsPackage: com.eugene.springcloud.example.user.enumeration
  typeAliasesPackage: com.eugene.springcloud.exampl.user.pojo.domain
  global-config:
    db-config:
      id-type: uuid
feign:
  # Hystrix的支持，如果为true，hystrix库必须在classpath中
  hystrix:
    enabled: true
  # 请求和响应GZIP压缩支持
  compression:
    request:
      enabled: true
      #支持压缩的MIME TYPES
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
